run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - execinquery  # deprecated
    - gomnd  # deprecated
    - exportloopref  # deprecated
    - varnamelen  # too strict
    # - mnd  # too strict
    # - ireturn  # not revelant
    # - exhaustive  # not revelant
    # - exhaustruct  # not revelant

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 14
  goconst:
    min-len: 3
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 120
  forbidigo:
    forbid:
      - ^print(ln)?$
      - ^spew\.Print(f|ln)?$
      - ^spew\.Dump$
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
  godox:
    keywords:
      - FIXME
  revive:
    rules:
      - name: struct-tag
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
        disabled: true
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id
  staticcheck:
    checks:
      - all
  cyclop:
    max-complexity: 12

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: '(.+)_test.go'
      linters:
        - forcetypeassert
        - govet
        - dupword
    - path: 'iter.go'
      text: 'File is not `gci`-ed with --skip-generated -s standard -s default'
      linters:
        - gci
    - path: 'iter_test.go'
      text: 'File is not `gci`-ed with --skip-generated -s standard -s default'
      linters:
        - gci
