name: Release

on:
  release:

permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref }}
          REPO_NAME: ${{ github.event.repository.name }}
        with:
          script: |
            // Get the version from the tag
            const tag = process.env.TAG_NAME.replace('refs/tags/', '');

            github.rest.repos.createRelease({
              owner: process.env.GITHUB_REPOSITORY.split('/')[0],
              repo: process.env.REPO_NAME,
              tag_name: tag,
              generate_release_notes: true,
            });
